# Generated by Django 2.2.13 on 2021-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('user_avatarurl', models.CharField(max_length=128, unique=True, verbose_name='avatar')),
                ('user_id', models.CharField(max_length=128, unique=True, verbose_name='user_id')),
                ('is_manager', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
