# Generated by Django 3.0.7 on 2021-03-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatarurl', models.CharField(max_length=128, verbose_name='avatar')),
                ('user_id', models.CharField(max_length=128, unique=True, verbose_name='user_id')),
                ('is_manager', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
