# Generated by Django 2.2.13 on 2021-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatarurl',
            field=models.CharField(max_length=128, verbose_name='avatar'),
        ),
    ]
