# Generated by Django 2.2.13 on 2021-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookinfo_sign', models.CharField(max_length=128)),
                ('siteinfo_sign', models.CharField(max_length=128)),
                ('user_nickname', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('user_avatar', models.CharField(max_length=128)),
                ('bookinfo_status', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteinfo_sign', models.CharField(max_length=128)),
                ('title_book', models.CharField(max_length=128)),
                ('time_book', models.CharField(max_length=128)),
                ('site_book', models.CharField(max_length=128)),
                ('zone_book', models.CharField(max_length=128)),
                ('payment_method', models.CharField(max_length=128)),
                ('limit_number', models.IntegerField()),
                ('remaining_places', models.IntegerField()),
                ('manager_id', models.CharField(max_length=128)),
            ],
        ),
    ]
