# Generated by Django 3.0.7 on 2021-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210325_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='site_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
